pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - approved-reviews-by>=1
      - base=main
      - -closed
      - -conflict
      - -draft
    actions:
      merge:
        method: merge
